"""
MQR (Möbius Quantum Ring) package.

This package implements the algorithm described in `Möbius Quantum Ring.html`:
- Unistochastic manifold parameterization: H = |U|^2 with U generated by Cayley transform
- Headless ring dynamics: fixed-point relaxation with dissipation/injection coefficient alpha
- Hamiltonian (LoRA-style) low-rank injection: J(x) = W_up W_down x
- Local projective sampling readout: y = W_readout * h*_S
"""

from .unitary import CayleyUnistochasticParam
from .ring import MoebiusQuantumRing, MoebiusQuantumRingImageClassifier, create_mobius_model

__all__ = [
    "CayleyUnistochasticParam",
    "MoebiusQuantumRing",
    "MoebiusQuantumRingImageClassifier",
    "create_mobius_model",
]

